package shiro_test

/**
 * Generated by the Shiro plugin. This filters class protects all URLs
 * via access control by convention.
 */
class SecurityFilters {
	
	def publicActions = [
		signup: ['*'],
		home: ['*'],
		auth:['*']	
	]
	
	private boolean findAction(controllerName, actionName){
		def c = publicActions[controllerName]
		return(c)?c.find{(it==actionName || it=='*')}!=null:false
	}
	
	def filters = {
		all(uri: "/**"){
			before = {
				def isPublic = findAction(controllerName,actionName)
				
				if(isPublic){
					return true
				}
				
				if (!controllerName || controllerName == 'assets'){
					return true
				}
				
				accessControl()
			}
		}
	}
}
